# Generated by Django 5.2.7 on 2025-10-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_root_rename_home_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Root',
        ),
    ]
