[tool.poetry]
name = "apecs"
version = "0.0.1"
description = ""
authors = ["Axel Schlindwein <axel.schlindwein@uit.no>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13" # EOL 2029-10, bugfix 2026-10
django = "^5.2.7" # EOL 2028-03
wagtail = "^6.0" # EOL 2026-10
django-htmx = "^1.26.0"
posthog = "^6.7.6"
sentry-sdk = "^2.41.0"
gunicorn = "^23.0.0"
gevent = "^25.9.1"
boto3 = "^1.40.49"
django-storages = "^1.14.4"
whitenoise = "^6.11.0"
psycopg2-binary = "^2.9.9"
wagtail-modeladmin = "^2.2.0"
celery = "^5.5.3"
django-celery-beat = "^2.8.1"
django-celery-results = "^2.6.0"
redis = "^6.4.0"
pillow = "^11.3.0"
load-dotenv = "^0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"