[project]
name = "apecs"
version = "0.0.1"
description = ""
authors = [
    {name = "Axel Schlindwein", email = "axel.schlindwein@uit.no>"}
]
readme = "README.md"
dynamic = [ "dependencies" ]
requires-python = "~=3.13.7" # EOL 2029-10, bugfix 2026-10

[tool.poetry.dependencies]
django = "~=5.2.8" # EOL 2028-03
wagtail = "7.0" # EOL 2026-10
redis = "^7.0.0"
celery = "^5.5.3"
gunicorn = "^23.0.0"
gevent = "^25.9.1"
boto3 = "^1.40.49"
psycopg2-binary = "^2.9.9"
pillow = "^11.3.0"
django-storages = "^1.14.4"
django-celery-beat = "^2.8.1"
django-celery-results = "^2.6.0"
django-htmx = "^1.26.0"
wagtail-modeladmin = "^2.2.0"
whitenoise = "^6.11.0"
posthog = "^6.7.6"
sentry-sdk = "^2.41.0"
setuptools="^80.9.0"
load-dotenv = "^0.1.0"
poetry-core = "^2.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"