# Generated by Django 5.2.7 on 2025-10-18 12:35

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4), ('checklist', 7), ('quote', 10), ('related_material', 16), ('box', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'Heading'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Task description', 'max_length': 255, 'required': True}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('items', 6)]], {}), 8: ('wagtail.blocks.TextBlock', (), {'help_text': 'Enter the quote text', 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Quote author (optional)', 'max_length': 100, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('quote', 8), ('author', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the resource', 'max_length': 100, 'required': True}), 12: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short description of the resource', 'required': False}), 13: ('wagtail.blocks.URLBlock', (), {'help_text': 'External link to the resource', 'required': True}), 14: ('wagtail.blocks.StructBlock', [[('title', 11), ('description', 12), ('url', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'max_num': 3, 'min_num': 1}), 16: ('wagtail.blocks.StructBlock', [[('resources', 15)]], {}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('warning', 'Warning'), ('note', 'Note')], 'help_text': "Select if it's a warning or note."}), 18: ('wagtail.blocks.TextBlock', (), {'help_text': 'The content of the warning or note box.', 'required': True}), 19: ('wagtail.blocks.StructBlock', [[('box_type', 17), ('content', 18)]], {})})),
                ('references', wagtail.fields.StreamField([('reference', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Abbreviation of the reference', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the reference', 'required': True}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link to the reference', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('short', 0), ('text', 1), ('url', 2)]], {})})),
                ('access', models.CharField(choices=[('na', 'undefined'), ('public', 'public'), ('internal', 'internal'), ('none', 'no access')], default='na', max_length=32)),
                ('authors', models.ManyToManyField(blank=True, related_name='article_authors', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(blank=True, related_name='article_editors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.article')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Guidebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('articles', models.ManyToManyField(default='na', through='compass.Chapter', to='compass.article')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='guidebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.guidebook'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('guidebook', 'article')},
        ),
    ]
