# Generated by Django 5.2.8 on 2026-10-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0002_resourcetype_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetype',
            name='display_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
