# Generated by Django 5.2.8 on 2026-10-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0004_resource_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('planning', 'Fieldwork planning'), ('safety', 'Safety'), ('logistics', 'Logistics, permits and regulations'), ('collaboration', 'Ethical and equitable collaboration'), ('environment', 'Reducing environmental impact'), ('instrumentation', 'Scientific instrumentation and data acquisition'), ('data', 'Data management and analysis'), ('communication', 'Science communication'), ('other', 'Other')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='resources', to='compass.resourcecategory'),
        ),
    ]
