# Generated by Django 5.2.8 on 2026-10-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0005_resourcecategory_remove_resource_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='category',
            new_name='categories',
        ),
        migrations.RemoveField(
            model_name='resourcecategory',
            name='category',
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
