# Generated by Django 5.2.8 on 2026-10-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0006_rename_category_resource_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='resources', to='compass.resourcekeyword'),
        ),
    ]
