# Generated by Django 5.2.8 on 2026-10-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0007_resourcekeyword_resource_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='environment',
            field=models.ManyToManyField(blank=True, related_name='resources', to='compass.resourceenvironment'),
        ),
        migrations.AddField(
            model_name='resource',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='resources', to='compass.resourceregion'),
        ),
    ]
