# Generated by Django 5.2.8 on 2026-10-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0008_resourceenvironment_resourceregion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='environment',
            new_name='environments',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='region',
            new_name='regions',
        ),
    ]
