# Generated by Django 5.1.1 on 2024-12-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apecsauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
